apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtls-server
---
apiVersion: v1
kind: Service
metadata:
  name: mtls-server
  labels:
    app: mtls-server
    service: mtls-server
spec:
  ports:
  - port: 3000
    name: http
  selector:
    app: mtls-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-server
  labels:
    app: mtls-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-server
  template:
    metadata:
      labels:
        app: mtls-server
    spec:
      serviceAccountName: mtls-server
      containers:
      - name: mtls-server
        image: docker.io/linsun/mtls-server:latest
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
