apiVersion: v1
kind: ServiceAccount
metadata:
  name: mtls-client
---
apiVersion: v1
kind: Service
metadata:
  name: mtls-client
  labels:
    app: mtls-client
    service: mtls-client
spec:
  ports:
  - port: 80
    name: http
  selector:
    app: mtls-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls-client
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mtls-client
  template:
    metadata:
      labels:
        app: mtls-client
    spec:
      terminationGracePeriodSeconds: 0
      serviceAccountName: mtls-client
      containers:
      - name: mtls-client
        image: linsun/mtls-client:latest
        command: ["/bin/sleep", "infinity"]
        imagePullPolicy: Always
---